### ISSUE TITLE
Crashes on server load

### ISSUE THREAD

**Issue by Aetheros** [daedalus4096/ThaumicWonders#3] opened 2019-03-21 20:32 UTC
Description of the Issue:
The server crashes if the specified version is installed. Was fine before update

Version: 1.1.0

Stack Trace: https://pastebin.com/tgzcg0Wj

Steps to reproduce:

Put the new version on a server.

**Comment by daedalus4096** [comment] 2019-03-22 02:51
This bug should be fixed in v1.1.1, which should be available on CurseForge later this evening.

**Comment by Aetheros** [comment] 2019-03-22 11:40
[crash-2019-03-22_12.35.12-server.txt](https://github.com/daedalus4096/ThaumicWonders/files/2996295/crash-2019-03-22_12.35.12-server.txt)

Still crashing. Here is the full log.

**Comment by daedalus4096** [comment] 2019-03-23 04:07
Strange.  I couldn't reproduce this after my initial fix.  I'll take another look.

**Comment by daedalus4096** [comment] 2019-03-23 04:28
Okay, the fix should stick this time.  Please try again with v1.2.0.

**Closed by daedalus4096** 2019-03-23 04:28 UTC
